stages:
  - build
  - test

.elixir:
  image: elixir:1.11.3
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - _build
      - deps

compile:
  stage: build
  extends: ".elixir"
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix compile --warnings-as-errors

test:
  stage: test
  extends: ".elixir"
  services:
    - postgres:13.2-alpine
  variables:
    POSTGRES_DB: xray_test
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
    MIX_ENV: "test"
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix ecto.setup
    - mix coveralls.json
    - bash <(curl -s https://codecov.io/bash)

lint:
  stage: test
  extends: ".elixir"
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix format --check-formatted
    - mix credo --strict
